[package]
name = "scheduler-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.4.1"
chrono = { version = "0.4.31", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.10.1"
lazy_static = "1.4.0"
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
sqlx = { version = "0.7.3", features = [ "mysql", "chrono", "uuid"] }
uuid = { version = "1.6.1", features = ["v4"] }
